-- PostgreSQL table structure for opennutrition_foods_cleaned_expanded.tsv
-- This table can be imported into Supabase

CREATE TABLE IF NOT EXISTS opennutrition_foods (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    added_sugars NUMERIC(10, 3),
    alanine NUMERIC(10, 3),
    alpha_linolenic_acid NUMERIC(10, 3),
    arachidonic_acid NUMERIC(10, 3),
    arginine NUMERIC(10, 3),
    aspartic_acid NUMERIC(10, 3),
    biotin NUMERIC(10, 3),
    caffeine NUMERIC(10, 3),
    calcium NUMERIC(10, 3),
    calories NUMERIC(10, 3),
    capric_acid NUMERIC(10, 3),
    caprylic_acid NUMERIC(10, 3),
    carbohydrates NUMERIC(10, 3),
    chlorine NUMERIC(10, 3),
    cholesterol NUMERIC(10, 3),
    choline NUMERIC(10, 3),
    chromium NUMERIC(10, 3),
    copper NUMERIC(10, 3),
    cysteine NUMERIC(10, 3),
    cystine NUMERIC(10, 3),
    dietary_fiber NUMERIC(10, 3),
    dihomo_gamma_linolenic_acid NUMERIC(10, 3),
    docosahexaenoic_acid NUMERIC(10, 3),
    docosapentaenoic_acid NUMERIC(10, 3),
    eicosapentaenoic_acid NUMERIC(10, 3),
    eicosenoic_acid NUMERIC(10, 3),
    erucic_acid NUMERIC(10, 3),
    ethyl_alcohol NUMERIC(10, 3),
    folate_dfe NUMERIC(10, 3),
    folic_acid NUMERIC(10, 3),
    gamma_linolenic_acid NUMERIC(10, 3),
    glutamic_acid NUMERIC(10, 3),
    glycine NUMERIC(10, 3),
    histidine NUMERIC(10, 3),
    insoluble_fiber NUMERIC(10, 3),
    iodine NUMERIC(10, 3),
    iron NUMERIC(10, 3),
    isoleucine NUMERIC(10, 3),
    lauric_acid NUMERIC(10, 3),
    leucine NUMERIC(10, 3),
    linoleic_acid NUMERIC(10, 3),
    linolenic_acid NUMERIC(10, 3),
    lysine NUMERIC(10, 3),
    magnesium NUMERIC(10, 3),
    manganese NUMERIC(10, 3),
    methionine NUMERIC(10, 3),
    molybdenum NUMERIC(10, 3),
    monounsaturated_fats NUMERIC(10, 3),
    myristic_acid NUMERIC(10, 3),
    niacin NUMERIC(10, 3),
    oleic_acid NUMERIC(10, 3),
    omega_3 NUMERIC(10, 3),
    omega_6 NUMERIC(10, 3),
    omega_9 NUMERIC(10, 3),
    other_carbohydrates NUMERIC(10, 3),
    palmitic_acid NUMERIC(10, 3),
    pantothenic_acid NUMERIC(10, 3),
    phenylalanine NUMERIC(10, 3),
    phosphorus NUMERIC(10, 3),
    polyunsaturated_fats NUMERIC(10, 3),
    potassium NUMERIC(10, 3),
    proline NUMERIC(10, 3),
    protein NUMERIC(10, 3),
    riboflavin NUMERIC(10, 3),
    saturated_fats NUMERIC(10, 3),
    selenium NUMERIC(10, 3),
    serine NUMERIC(10, 3),
    sodium NUMERIC(10, 3),
    soluble_fiber NUMERIC(10, 3),
    sorbitol NUMERIC(10, 3),
    stearic_acid NUMERIC(10, 3),
    sugar_alcohols NUMERIC(10, 3),
    taurine NUMERIC(10, 3),
    thiamin NUMERIC(10, 3),
    threonine NUMERIC(10, 3),
    total_fat NUMERIC(10, 3),
    total_folate NUMERIC(10, 3),
    total_sugars NUMERIC(10, 3),
    trans_fats NUMERIC(10, 3),
    tryptophan NUMERIC(10, 3),
    tyrosine NUMERIC(10, 3),
    undefined NUMERIC(10, 3),
    valine NUMERIC(10, 3),
    vitamin_a NUMERIC(10, 3),
    vitamin_a_iu NUMERIC(10, 3),
    vitamin_b12 NUMERIC(10, 3),
    vitamin_b6 NUMERIC(10, 3),
    vitamin_c NUMERIC(10, 3),
    vitamin_d NUMERIC(10, 3),
    vitamin_d3 NUMERIC(10, 3),
    vitamin_d_iu NUMERIC(10, 3),
    vitamin_e NUMERIC(10, 3),
    vitamin_e_alpha NUMERIC(10, 3),
    vitamin_k NUMERIC(10, 3),
    water NUMERIC(10, 3),
    xylitol NUMERIC(10, 3),
    zinc NUMERIC(10, 3)
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_opennutrition_foods_name ON opennutrition_foods USING gin(to_tsvector('english', name));

-- Optional: Create a full-text search index on name
-- This allows for efficient text search on food names

COMMENT ON TABLE opennutrition_foods IS 'OpenNutrition foods database with expanded nutrition columns';
COMMENT ON COLUMN opennutrition_foods.id IS 'Unique food identifier';
COMMENT ON COLUMN opennutrition_foods.name IS 'Food name';
COMMENT ON COLUMN opennutrition_foods.calories IS 'Calories per 100g';
COMMENT ON COLUMN opennutrition_foods.protein IS 'Protein per 100g in grams';
