// Reference values (per day) for all nutrients displayed in DetailsNaehrstoffprofilComponent.
// Replace the placeholder numbers with your actual guideline values as needed.
export const nutrientReferences: Record<string, number> = {
  // Überblick
  Energie: 0,
  Eiweiß: 0,
  Gesamtfett: 0,
  Kohlenhydrate: 0,
  Ballaststoffe: 0,
  Cholesterin: 0,
  Wasser: 0,
  Alkohol: 0,

  // Vitamine
  "Vitamin A": 0,
  "Vitamin A (IU)": 0,
  "Vitamin B6": 0,
  "Vitamin B12": 0,
  "Vitamin C": 0,
  "Vitamin D": 0,
  "Vitamin D3": 0,
  "Vitamin D (IU)": 0,
  "Vitamin E": 0,
  "Vitamin E Alpha": 0,
  "Vitamin K": 0,
  Thiamin: 0,
  Riboflavin: 0,
  Niacin: 0,
  Pantothensäure: 0,
  Biotin: 0,
  Folsäure: 0,
  "Folat (DFE)": 0,
  Gesamtfolat: 0,

  // Mengenelemente
  Calcium: 0,
  Chlorid: 0,
  Magnesium: 0,
  Phosphor: 0,
  Kalium: 0,
  Natrium: 0,

  // Spurenelemente
  Chrom: 0,
  Kupfer: 0,
  Iod: 0,
  Eisen: 0,
  Mangan: 0,
  Molybdän: 0,
  Selen: 0,
  Zink: 0,

  // Kohlenhydrate
  Kohlenhydrate: 0,
  Gesamtzucker: 0,
  "Hinzugefügte Zucker": 0,
  "Andere Kohlenhydrate": 0,
  "Lösliche Faser": 0,
  "Unlösliche Faser": 0,
  Zuckeralkohole: 0,
  Sorbit: 0,
  Xylit: 0,

  // Aminosäuren
  Alanin: 0,
  Arginin: 0,
  Asparaginsäure: 0,
  Cystin: 0,
  Cystein: 0,
  Glutaminsäure: 0,
  Glycin: 0,
  Histidin: 0,
  Isoleucin: 0,
  Leucin: 0,
  Lysin: 0,
  Methionin: 0,
  Phenylalanin: 0,
  Prolin: 0,
  Serin: 0,
  Threonin: 0,
  Tryptophan: 0,
  Tyrosin: 0,
  Valin: 0,
  Taurin: 0,

  // Fettsäuren
  "Gesättigte Fettsäuren": 0,
  "Einfach ungesättigte Fettsäuren": 0,
  "Mehrfach ungesättigte Fettsäuren": 0,
  Transfette: 0,
  "Omega 3": 0,
  "Omega 6": 0,
  "Omega 9": 0,
  Laurinsäure: 0,
  Myristinsäure: 0,
  Palmitinsäure: 0,
  Stearinsäure: 0,
  Ölsäure: 0,
  Linolsäure: 0,
  Linolensäure: 0,
  "Alpha-Linolensäure": 0,
  Arachidonsäure: 0,
  "Dihomo-Gamma-Linolensäure": 0,
  "Docosahexaensäure (DHA)": 0,
  "Docosapentaensäure (DPA)": 0,
  "Eicosapentaensäure (EPA)": 0,
  Eicosensäure: 0,
  Erucasäure: 0,
  Caprinsäure: 0,
  Caprylsäure: 0,

  // Sekundäre Pflanzenstoffe
  Koffein: 0,
  "Nicht zugeordnet": 0,
};
